// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiBMN.Data;

#nullable disable

namespace SiBMN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225052352_InitialCreateV4")]
    partial class InitialCreateV4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SiBMN.Models.AsetInventaris", b =>
                {
                    b.Property<int>("IdAset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_aset");

                    b.Property<int>("IdBarang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_barang");

                    b.Property<int>("IdRuang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_ruang");

                    b.Property<int>("KodeInventaris")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kode_inventaris");

                    b.Property<string>("Kondisi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("kondisi");

                    b.HasKey("IdAset");

                    b.HasIndex("IdBarang");

                    b.HasIndex("IdRuang");

                    b.ToTable("Aset_Inventaris");
                });

            modelBuilder.Entity("SiBMN.Models.DetailPengajuan", b =>
                {
                    b.Property<int>("IdDetPengajuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_detPengajuan");

                    b.Property<string>("AlasanImport")
                        .HasColumnType("TEXT")
                        .HasColumnName("alasan_import");

                    b.Property<string>("AsalBarang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("asal_barang");

                    b.Property<string>("FungsiBarang")
                        .HasColumnType("TEXT")
                        .HasColumnName("fungsi_barang");

                    b.Property<string>("GambarEkatalog")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("gambar_ekatalog");

                    b.Property<decimal>("HargaSatuan")
                        .HasColumnType("TEXT")
                        .HasColumnName("harga_satuan");

                    b.Property<int>("IdBarang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_barang");

                    b.Property<int>("IdPengajuan")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_pengajuan");

                    b.Property<int>("IdRuang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_ruang");

                    b.Property<int>("JumlahDiminta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("jumlah_diminta");

                    b.Property<int>("JumlahDisetujui")
                        .HasColumnType("INTEGER")
                        .HasColumnName("jumlah_disetujui");

                    b.Property<decimal>("JumlahHarga")
                        .HasColumnType("TEXT")
                        .HasColumnName("jumlah_harga");

                    b.Property<string>("LinkGambar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("link_gambar");

                    b.Property<string>("LinkSurvey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("link_survey");

                    b.Property<int?>("MasterBarangIdBarang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoPrioritas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("no_prioritas");

                    b.Property<string>("Spesifikasi")
                        .HasColumnType("TEXT")
                        .HasColumnName("spesifikasi");

                    b.HasKey("IdDetPengajuan");

                    b.HasIndex("IdBarang");

                    b.HasIndex("IdPengajuan");

                    b.HasIndex("IdRuang");

                    b.HasIndex("MasterBarangIdBarang");

                    b.ToTable("Detail_Pengajuan");
                });

            modelBuilder.Entity("SiBMN.Models.KategoriBarang", b =>
                {
                    b.Property<int>("IdKategori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_kategori");

                    b.Property<string>("NamaKategori")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nama_kategori");

                    b.HasKey("IdKategori");

                    b.ToTable("Kategori_Barang");

                    b.HasData(
                        new
                        {
                            IdKategori = 1,
                            NamaKategori = "Peralatan dan Mesin"
                        },
                        new
                        {
                            IdKategori = 2,
                            NamaKategori = "Gedung dan Bangunan"
                        },
                        new
                        {
                            IdKategori = 3,
                            NamaKategori = "Jalan, Irigasi dan Jaringan"
                        },
                        new
                        {
                            IdKategori = 4,
                            NamaKategori = "Aset Tetap Lainnya"
                        });
                });

            modelBuilder.Entity("SiBMN.Models.KodeBarang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("KodeBarangValue")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("kode_barang_value");

                    b.Property<string>("KodeBidang")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("kode_bidang");

                    b.Property<string>("KodeGolongan")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("kode_golongan");

                    b.Property<string>("KodeKelompok")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("kode_kelompok");

                    b.Property<string>("KodeSubKelompok")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("kode_sub_kelompok");

                    b.Property<string>("UraianBarang")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("uraian_barang");

                    b.HasKey("Id");

                    b.HasIndex("KodeGolongan", "KodeBidang", "KodeKelompok", "KodeSubKelompok", "KodeBarangValue")
                        .IsUnique();

                    b.ToTable("Kode_Barang");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KodeBarangValue = "000",
                            KodeBidang = "00",
                            KodeGolongan = "1",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Barang Kuasi"
                        },
                        new
                        {
                            Id = 2,
                            KodeBarangValue = "000",
                            KodeBidang = "00",
                            KodeGolongan = "2",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Tanah"
                        },
                        new
                        {
                            Id = 3,
                            KodeBarangValue = "000",
                            KodeBidang = "00",
                            KodeGolongan = "3",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Peralatan dan Mesin"
                        },
                        new
                        {
                            Id = 4,
                            KodeBarangValue = "000",
                            KodeBidang = "00",
                            KodeGolongan = "4",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Gedung dan Bangunan"
                        },
                        new
                        {
                            Id = 5,
                            KodeBarangValue = "000",
                            KodeBidang = "00",
                            KodeGolongan = "5",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Jalan, Irigasi dan Jaringan"
                        },
                        new
                        {
                            Id = 6,
                            KodeBarangValue = "000",
                            KodeBidang = "00",
                            KodeGolongan = "6",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Aset Tetap Lainnya"
                        },
                        new
                        {
                            Id = 10,
                            KodeBarangValue = "000",
                            KodeBidang = "01",
                            KodeGolongan = "3",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Besar"
                        },
                        new
                        {
                            Id = 11,
                            KodeBarangValue = "000",
                            KodeBidang = "02",
                            KodeGolongan = "3",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Angkutan"
                        },
                        new
                        {
                            Id = 12,
                            KodeBarangValue = "000",
                            KodeBidang = "03",
                            KodeGolongan = "3",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Bengkel dan Alat Ukur"
                        },
                        new
                        {
                            Id = 13,
                            KodeBarangValue = "000",
                            KodeBidang = "04",
                            KodeGolongan = "3",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Pertanian"
                        },
                        new
                        {
                            Id = 14,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Kantor dan Rumah Tangga"
                        },
                        new
                        {
                            Id = 15,
                            KodeBarangValue = "000",
                            KodeBidang = "06",
                            KodeGolongan = "3",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Studio, Komunikasi dan Pemancar"
                        },
                        new
                        {
                            Id = 16,
                            KodeBarangValue = "000",
                            KodeBidang = "07",
                            KodeGolongan = "3",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Kedokteran dan Kesehatan"
                        },
                        new
                        {
                            Id = 17,
                            KodeBarangValue = "000",
                            KodeBidang = "08",
                            KodeGolongan = "3",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Laboratorium"
                        },
                        new
                        {
                            Id = 18,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Komputer"
                        },
                        new
                        {
                            Id = 19,
                            KodeBarangValue = "000",
                            KodeBidang = "01",
                            KodeGolongan = "4",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Bangunan Gedung"
                        },
                        new
                        {
                            Id = 20,
                            KodeBarangValue = "000",
                            KodeBidang = "02",
                            KodeGolongan = "4",
                            KodeKelompok = "00",
                            KodeSubKelompok = "00",
                            UraianBarang = "Monumen"
                        },
                        new
                        {
                            Id = 21,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Kantor"
                        },
                        new
                        {
                            Id = 22,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Rumah Tangga"
                        },
                        new
                        {
                            Id = 23,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "03",
                            KodeSubKelompok = "00",
                            UraianBarang = "Peralatan Komputer"
                        },
                        new
                        {
                            Id = 24,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "00",
                            UraianBarang = "Komputer Unit"
                        },
                        new
                        {
                            Id = 25,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "00",
                            UraianBarang = "Peralatan Komputer"
                        },
                        new
                        {
                            Id = 26,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "03",
                            KodeSubKelompok = "00",
                            UraianBarang = "Peralatan Jaringan"
                        },
                        new
                        {
                            Id = 27,
                            KodeBarangValue = "000",
                            KodeBidang = "01",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Besar Darat"
                        },
                        new
                        {
                            Id = 28,
                            KodeBarangValue = "000",
                            KodeBidang = "01",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "00",
                            UraianBarang = "Alat Besar Apung"
                        },
                        new
                        {
                            Id = 30,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "01",
                            UraianBarang = "Mesin Ketik"
                        },
                        new
                        {
                            Id = 31,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "02",
                            UraianBarang = "Mesin Hitung/Jumlah"
                        },
                        new
                        {
                            Id = 32,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Alat Penyimpanan Perlengkapan Kantor"
                        },
                        new
                        {
                            Id = 33,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "04",
                            UraianBarang = "Alat Kantor Lainnya"
                        },
                        new
                        {
                            Id = 34,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "01",
                            UraianBarang = "Meubelair"
                        },
                        new
                        {
                            Id = 35,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "02",
                            UraianBarang = "Alat Pendingin"
                        },
                        new
                        {
                            Id = 36,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "03",
                            UraianBarang = "Alat Dapur"
                        },
                        new
                        {
                            Id = 37,
                            KodeBarangValue = "000",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "04",
                            UraianBarang = "Alat Pembersih"
                        },
                        new
                        {
                            Id = 38,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "01",
                            UraianBarang = "Komputer/PC"
                        },
                        new
                        {
                            Id = 39,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "02",
                            UraianBarang = "Laptop/Notebook"
                        },
                        new
                        {
                            Id = 40,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Server"
                        },
                        new
                        {
                            Id = 41,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "01",
                            UraianBarang = "Peralatan Mainframe"
                        },
                        new
                        {
                            Id = 42,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "02",
                            UraianBarang = "Peralatan Mini Komputer"
                        },
                        new
                        {
                            Id = 43,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "03",
                            UraianBarang = "Peralatan Personal Komputer"
                        },
                        new
                        {
                            Id = 50,
                            KodeBarangValue = "001",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Lemari Besi/Metal"
                        },
                        new
                        {
                            Id = 51,
                            KodeBarangValue = "002",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Lemari Kayu"
                        },
                        new
                        {
                            Id = 52,
                            KodeBarangValue = "003",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Rak Besi/Metal"
                        },
                        new
                        {
                            Id = 53,
                            KodeBarangValue = "004",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Rak Kayu"
                        },
                        new
                        {
                            Id = 54,
                            KodeBarangValue = "005",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Filing Cabinet Besi"
                        },
                        new
                        {
                            Id = 55,
                            KodeBarangValue = "006",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Brand Kas"
                        },
                        new
                        {
                            Id = 56,
                            KodeBarangValue = "001",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "01",
                            UraianBarang = "Meja Kerja"
                        },
                        new
                        {
                            Id = 57,
                            KodeBarangValue = "002",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "01",
                            UraianBarang = "Meja Rapat"
                        },
                        new
                        {
                            Id = 58,
                            KodeBarangValue = "003",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "01",
                            UraianBarang = "Kursi Kerja"
                        },
                        new
                        {
                            Id = 59,
                            KodeBarangValue = "004",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "01",
                            UraianBarang = "Kursi Tamu"
                        },
                        new
                        {
                            Id = 60,
                            KodeBarangValue = "005",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "01",
                            UraianBarang = "Tempat Tidur"
                        },
                        new
                        {
                            Id = 61,
                            KodeBarangValue = "006",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "01",
                            UraianBarang = "Sofa"
                        },
                        new
                        {
                            Id = 62,
                            KodeBarangValue = "001",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "02",
                            UraianBarang = "AC Split"
                        },
                        new
                        {
                            Id = 63,
                            KodeBarangValue = "002",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "02",
                            UraianBarang = "AC Window"
                        },
                        new
                        {
                            Id = 64,
                            KodeBarangValue = "003",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "02",
                            UraianBarang = "Kipas Angin"
                        },
                        new
                        {
                            Id = 65,
                            KodeBarangValue = "004",
                            KodeBidang = "05",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "02",
                            UraianBarang = "Exhaust Fan"
                        },
                        new
                        {
                            Id = 66,
                            KodeBarangValue = "001",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "01",
                            UraianBarang = "PC Desktop"
                        },
                        new
                        {
                            Id = 67,
                            KodeBarangValue = "002",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "01",
                            UraianBarang = "PC All-in-One"
                        },
                        new
                        {
                            Id = 68,
                            KodeBarangValue = "003",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "01",
                            UraianBarang = "PC Mini/NUC"
                        },
                        new
                        {
                            Id = 69,
                            KodeBarangValue = "001",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "02",
                            UraianBarang = "Laptop 14 inch"
                        },
                        new
                        {
                            Id = 70,
                            KodeBarangValue = "002",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "02",
                            UraianBarang = "Laptop 15 inch"
                        },
                        new
                        {
                            Id = 71,
                            KodeBarangValue = "003",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "02",
                            UraianBarang = "Notebook Ultrabook"
                        },
                        new
                        {
                            Id = 72,
                            KodeBarangValue = "001",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "03",
                            UraianBarang = "Printer Laser"
                        },
                        new
                        {
                            Id = 73,
                            KodeBarangValue = "002",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "03",
                            UraianBarang = "Printer Inkjet"
                        },
                        new
                        {
                            Id = 74,
                            KodeBarangValue = "003",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "03",
                            UraianBarang = "Scanner"
                        },
                        new
                        {
                            Id = 75,
                            KodeBarangValue = "004",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "03",
                            UraianBarang = "Monitor LED"
                        },
                        new
                        {
                            Id = 76,
                            KodeBarangValue = "005",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "03",
                            UraianBarang = "Proyektor LCD"
                        },
                        new
                        {
                            Id = 77,
                            KodeBarangValue = "006",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "03",
                            UraianBarang = "UPS"
                        },
                        new
                        {
                            Id = 78,
                            KodeBarangValue = "007",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "03",
                            UraianBarang = "Keyboard"
                        },
                        new
                        {
                            Id = 79,
                            KodeBarangValue = "008",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "02",
                            KodeSubKelompok = "03",
                            UraianBarang = "Mouse"
                        },
                        new
                        {
                            Id = 80,
                            KodeBarangValue = "000",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "03",
                            KodeSubKelompok = "01",
                            UraianBarang = "Peralatan Jaringan LAN"
                        },
                        new
                        {
                            Id = 81,
                            KodeBarangValue = "001",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "03",
                            KodeSubKelompok = "01",
                            UraianBarang = "Router WiFi"
                        },
                        new
                        {
                            Id = 82,
                            KodeBarangValue = "002",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "03",
                            KodeSubKelompok = "01",
                            UraianBarang = "Switch Managed"
                        },
                        new
                        {
                            Id = 83,
                            KodeBarangValue = "003",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "03",
                            KodeSubKelompok = "01",
                            UraianBarang = "Access Point"
                        },
                        new
                        {
                            Id = 84,
                            KodeBarangValue = "004",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "03",
                            KodeSubKelompok = "01",
                            UraianBarang = "CCTV IP Camera"
                        },
                        new
                        {
                            Id = 85,
                            KodeBarangValue = "001",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Server Tower"
                        },
                        new
                        {
                            Id = 86,
                            KodeBarangValue = "002",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Server Rack"
                        },
                        new
                        {
                            Id = 87,
                            KodeBarangValue = "003",
                            KodeBidang = "09",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "03",
                            UraianBarang = "Server Blade"
                        },
                        new
                        {
                            Id = 88,
                            KodeBarangValue = "000",
                            KodeBidang = "01",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "01",
                            UraianBarang = "Traktor"
                        },
                        new
                        {
                            Id = 89,
                            KodeBarangValue = "001",
                            KodeBidang = "01",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "01",
                            UraianBarang = "Traktor Roda Dua"
                        },
                        new
                        {
                            Id = 90,
                            KodeBarangValue = "002",
                            KodeBidang = "01",
                            KodeGolongan = "3",
                            KodeKelompok = "01",
                            KodeSubKelompok = "01",
                            UraianBarang = "Traktor Roda Empat"
                        });
                });

            modelBuilder.Entity("SiBMN.Models.MasterBarang", b =>
                {
                    b.Property<int>("IdBarang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_barang");

                    b.Property<int>("IdKategori")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_kategori");

                    b.Property<string>("NamaBarang")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("nama_barang");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("satuan");

                    b.Property<string>("Spesifikasi")
                        .HasColumnType("TEXT")
                        .HasColumnName("spesifikasi");

                    b.HasKey("IdBarang");

                    b.HasIndex("IdKategori");

                    b.ToTable("Master_Barang");

                    b.HasData(
                        new
                        {
                            IdBarang = 1,
                            IdKategori = 1,
                            NamaBarang = "Laptop",
                            Satuan = "Unit",
                            Spesifikasi = "Laptop untuk kebutuhan kantor"
                        },
                        new
                        {
                            IdBarang = 2,
                            IdKategori = 1,
                            NamaBarang = "Printer Laser",
                            Satuan = "Unit",
                            Spesifikasi = "Printer laser monochrome"
                        },
                        new
                        {
                            IdBarang = 3,
                            IdKategori = 1,
                            NamaBarang = "Proyektor",
                            Satuan = "Unit",
                            Spesifikasi = "Proyektor LCD"
                        },
                        new
                        {
                            IdBarang = 4,
                            IdKategori = 1,
                            NamaBarang = "AC Split",
                            Satuan = "Unit",
                            Spesifikasi = "AC Split 1 PK"
                        },
                        new
                        {
                            IdBarang = 5,
                            IdKategori = 1,
                            NamaBarang = "Komputer Desktop",
                            Satuan = "Unit",
                            Spesifikasi = "PC Desktop untuk kantor"
                        },
                        new
                        {
                            IdBarang = 6,
                            IdKategori = 1,
                            NamaBarang = "Scanner",
                            Satuan = "Unit",
                            Spesifikasi = "Scanner dokumen"
                        },
                        new
                        {
                            IdBarang = 7,
                            IdKategori = 1,
                            NamaBarang = "UPS",
                            Satuan = "Unit",
                            Spesifikasi = "Uninterruptible Power Supply"
                        },
                        new
                        {
                            IdBarang = 8,
                            IdKategori = 1,
                            NamaBarang = "Server Rack",
                            Satuan = "Unit",
                            Spesifikasi = "Server rack 42U"
                        },
                        new
                        {
                            IdBarang = 9,
                            IdKategori = 1,
                            NamaBarang = "Meja Kerja",
                            Satuan = "Buah",
                            Spesifikasi = "Meja kerja kayu"
                        },
                        new
                        {
                            IdBarang = 10,
                            IdKategori = 1,
                            NamaBarang = "Kursi Kerja",
                            Satuan = "Buah",
                            Spesifikasi = "Kursi kerja ergonomis"
                        },
                        new
                        {
                            IdBarang = 11,
                            IdKategori = 1,
                            NamaBarang = "Lemari Arsip",
                            Satuan = "Buah",
                            Spesifikasi = "Lemari arsip besi"
                        },
                        new
                        {
                            IdBarang = 12,
                            IdKategori = 1,
                            NamaBarang = "Whiteboard",
                            Satuan = "Buah",
                            Spesifikasi = "Papan tulis whiteboard"
                        },
                        new
                        {
                            IdBarang = 13,
                            IdKategori = 1,
                            NamaBarang = "Monitor LED",
                            Satuan = "Unit",
                            Spesifikasi = "Monitor LED 24 inch"
                        },
                        new
                        {
                            IdBarang = 14,
                            IdKategori = 1,
                            NamaBarang = "Router WiFi",
                            Satuan = "Unit",
                            Spesifikasi = "Router wireless enterprise"
                        },
                        new
                        {
                            IdBarang = 15,
                            IdKategori = 1,
                            NamaBarang = "CCTV Camera",
                            Satuan = "Unit",
                            Spesifikasi = "IP Camera outdoor"
                        });
                });

            modelBuilder.Entity("SiBMN.Models.MutasiAset", b =>
                {
                    b.Property<int>("IdMutasi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_mutasi");

                    b.Property<int>("IdAset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_aset");

                    b.Property<int>("IdRuang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_ruang");

                    b.Property<string>("TanggalMutasi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tanggal_mutasi");

                    b.HasKey("IdMutasi");

                    b.HasIndex("IdAset");

                    b.HasIndex("IdRuang");

                    b.ToTable("Mutasi_Aset");
                });

            modelBuilder.Entity("SiBMN.Models.PenerimaanBarang", b =>
                {
                    b.Property<int>("IdPenerimaan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_penerimaan");

                    b.Property<int>("IdPengajuan")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_pengajuan");

                    b.Property<DateTime>("TanggalTerima")
                        .HasColumnType("TEXT")
                        .HasColumnName("tanggal_terima");

                    b.HasKey("IdPenerimaan");

                    b.HasIndex("IdPengajuan");

                    b.ToTable("Penerimaan_Barang");
                });

            modelBuilder.Entity("SiBMN.Models.Pengajuan", b =>
                {
                    b.Property<int>("IdPengajuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_pengajuan");

                    b.Property<int?>("IdPejabat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_pejabat");

                    b.Property<string>("Jabatan")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("jabatan");

                    b.Property<string>("JenisPengajuan")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("jenis_pengajuan");

                    b.Property<string>("NoSuratRektor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("no_surat_rektor");

                    b.Property<int?>("NomorSurat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nomor_surat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("TahunAnggaran")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tahun_anggaran");

                    b.Property<DateTime>("TanggalPengajuan")
                        .HasColumnType("TEXT")
                        .HasColumnName("tanggal_pengajuan");

                    b.Property<DateTime?>("TglSuratRektor")
                        .HasColumnType("TEXT")
                        .HasColumnName("tgl_surat_rektor");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_harga");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_id");

                    b.HasKey("IdPengajuan");

                    b.HasIndex("IdPejabat");

                    b.HasIndex("UnitId");

                    b.ToTable("Pengajuan");
                });

            modelBuilder.Entity("SiBMN.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_role");

                    b.Property<string>("NamaRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nama_role");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            NamaRole = "Admin Unit Kerja"
                        },
                        new
                        {
                            IdRole = 2,
                            NamaRole = "Tim Pengadaan"
                        },
                        new
                        {
                            IdRole = 3,
                            NamaRole = "Admin Pusat"
                        },
                        new
                        {
                            IdRole = 4,
                            NamaRole = "Tim Kerja BMN"
                        });
                });

            modelBuilder.Entity("SiBMN.Models.RuangGedung", b =>
                {
                    b.Property<int>("IdRuang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_ruang");

                    b.Property<int>("IdUnit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_unit");

                    b.Property<string>("NamaGedung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nama_gedung");

                    b.Property<string>("NamaRuang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nama_ruang");

                    b.HasKey("IdRuang");

                    b.HasIndex("IdUnit");

                    b.ToTable("Ruang_Gedung");

                    b.HasData(
                        new
                        {
                            IdRuang = 1,
                            IdUnit = 4,
                            NamaGedung = "Gedung A - Rektorat",
                            NamaRuang = "Ruang Rapat Utama"
                        },
                        new
                        {
                            IdRuang = 2,
                            IdUnit = 4,
                            NamaGedung = "Gedung A - Rektorat",
                            NamaRuang = "Ruang Kerja Lantai 1"
                        },
                        new
                        {
                            IdRuang = 3,
                            IdUnit = 1,
                            NamaGedung = "Gedung B - Fakultas Teknik",
                            NamaRuang = "Lab Komputer 1"
                        },
                        new
                        {
                            IdRuang = 4,
                            IdUnit = 1,
                            NamaGedung = "Gedung B - Fakultas Teknik",
                            NamaRuang = "Lab Komputer 2"
                        },
                        new
                        {
                            IdRuang = 5,
                            IdUnit = 1,
                            NamaGedung = "Gedung B - Fakultas Teknik",
                            NamaRuang = "Ruang Dosen"
                        },
                        new
                        {
                            IdRuang = 6,
                            IdUnit = 2,
                            NamaGedung = "Gedung C - Fakultas Ekonomi",
                            NamaRuang = "Ruang Kelas 101"
                        },
                        new
                        {
                            IdRuang = 7,
                            IdUnit = 2,
                            NamaGedung = "Gedung C - Fakultas Ekonomi",
                            NamaRuang = "Ruang Dosen"
                        },
                        new
                        {
                            IdRuang = 8,
                            IdUnit = 3,
                            NamaGedung = "Gedung D - Fakultas Hukum",
                            NamaRuang = "Ruang Sidang"
                        },
                        new
                        {
                            IdRuang = 9,
                            IdUnit = 5,
                            NamaGedung = "Gedung E - Perpustakaan",
                            NamaRuang = "Ruang Baca"
                        },
                        new
                        {
                            IdRuang = 10,
                            IdUnit = 5,
                            NamaGedung = "Gedung E - Perpustakaan",
                            NamaRuang = "Ruang Server"
                        });
                });

            modelBuilder.Entity("SiBMN.Models.StokPersediaan", b =>
                {
                    b.Property<int>("IdStok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_stok");

                    b.Property<int>("IdBarang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_barang");

                    b.Property<int>("IdUnit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_unit");

                    b.Property<int>("JumlahStok")
                        .HasColumnType("INTEGER")
                        .HasColumnName("jumlah_stok");

                    b.HasKey("IdStok");

                    b.HasIndex("IdBarang");

                    b.HasIndex("IdUnit");

                    b.ToTable("Stok_Persediaan");
                });

            modelBuilder.Entity("SiBMN.Models.Unit", b =>
                {
                    b.Property<int>("IdUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_unit");

                    b.Property<string>("NamaUnit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nama_unit");

                    b.HasKey("IdUnit");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            IdUnit = 1,
                            NamaUnit = "Fakultas Teknik"
                        },
                        new
                        {
                            IdUnit = 2,
                            NamaUnit = "Fakultas Ekonomi"
                        },
                        new
                        {
                            IdUnit = 3,
                            NamaUnit = "Fakultas Hukum"
                        },
                        new
                        {
                            IdUnit = 4,
                            NamaUnit = "Rektorat"
                        },
                        new
                        {
                            IdUnit = 5,
                            NamaUnit = "UPT Perpustakaan"
                        });
                });

            modelBuilder.Entity("SiBMN.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_user");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nama");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_id");

                    b.HasKey("IdUser");

                    b.HasIndex("RoleId");

                    b.HasIndex("UnitId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            Email = "admin.teknik@univ.ac.id",
                            Nama = "Admin Teknik",
                            Password = "admin123",
                            RoleId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            IdUser = 2,
                            Email = "admin.ekonomi@univ.ac.id",
                            Nama = "Admin Ekonomi",
                            Password = "admin123",
                            RoleId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            IdUser = 3,
                            Email = "pengadaan@univ.ac.id",
                            Nama = "Tim Pengadaan",
                            Password = "admin123",
                            RoleId = 2,
                            UnitId = 4
                        },
                        new
                        {
                            IdUser = 4,
                            Email = "budi@univ.ac.id",
                            Nama = "Prof. Dr. Budi Santoso",
                            Password = "admin123",
                            RoleId = 3,
                            UnitId = 4
                        },
                        new
                        {
                            IdUser = 5,
                            Email = "siti@univ.ac.id",
                            Nama = "Dr. Siti Rahayu, M.Sc.",
                            Password = "admin123",
                            RoleId = 3,
                            UnitId = 4
                        },
                        new
                        {
                            IdUser = 6,
                            Email = "bmn@univ.ac.id",
                            Nama = "Tim BMN",
                            Password = "admin123",
                            RoleId = 4,
                            UnitId = 4
                        });
                });

            modelBuilder.Entity("SiBMN.Models.AsetInventaris", b =>
                {
                    b.HasOne("SiBMN.Models.MasterBarang", "MasterBarang")
                        .WithMany("AsetInventaris")
                        .HasForeignKey("IdBarang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiBMN.Models.RuangGedung", "RuangGedung")
                        .WithMany("AsetInventaris")
                        .HasForeignKey("IdRuang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterBarang");

                    b.Navigation("RuangGedung");
                });

            modelBuilder.Entity("SiBMN.Models.DetailPengajuan", b =>
                {
                    b.HasOne("SiBMN.Models.KodeBarang", "KodeBarang")
                        .WithMany()
                        .HasForeignKey("IdBarang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiBMN.Models.Pengajuan", "Pengajuan")
                        .WithMany("DetailPengajuans")
                        .HasForeignKey("IdPengajuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiBMN.Models.RuangGedung", "RuangGedung")
                        .WithMany("DetailPengajuans")
                        .HasForeignKey("IdRuang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiBMN.Models.MasterBarang", null)
                        .WithMany("DetailPengajuans")
                        .HasForeignKey("MasterBarangIdBarang");

                    b.Navigation("KodeBarang");

                    b.Navigation("Pengajuan");

                    b.Navigation("RuangGedung");
                });

            modelBuilder.Entity("SiBMN.Models.MasterBarang", b =>
                {
                    b.HasOne("SiBMN.Models.KategoriBarang", "KategoriBarang")
                        .WithMany("MasterBarangs")
                        .HasForeignKey("IdKategori")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KategoriBarang");
                });

            modelBuilder.Entity("SiBMN.Models.MutasiAset", b =>
                {
                    b.HasOne("SiBMN.Models.AsetInventaris", "AsetInventaris")
                        .WithMany("MutasiAsets")
                        .HasForeignKey("IdAset")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiBMN.Models.RuangGedung", "RuangGedung")
                        .WithMany("MutasiAsets")
                        .HasForeignKey("IdRuang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsetInventaris");

                    b.Navigation("RuangGedung");
                });

            modelBuilder.Entity("SiBMN.Models.PenerimaanBarang", b =>
                {
                    b.HasOne("SiBMN.Models.Pengajuan", "Pengajuan")
                        .WithMany("PenerimaanBarangs")
                        .HasForeignKey("IdPengajuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengajuan");
                });

            modelBuilder.Entity("SiBMN.Models.Pengajuan", b =>
                {
                    b.HasOne("SiBMN.Models.User", "Pejabat")
                        .WithMany()
                        .HasForeignKey("IdPejabat")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SiBMN.Models.Unit", "Unit")
                        .WithMany("Pengajuans")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pejabat");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("SiBMN.Models.RuangGedung", b =>
                {
                    b.HasOne("SiBMN.Models.Unit", "Unit")
                        .WithMany("RuangGedungs")
                        .HasForeignKey("IdUnit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("SiBMN.Models.StokPersediaan", b =>
                {
                    b.HasOne("SiBMN.Models.MasterBarang", "MasterBarang")
                        .WithMany("StokPersediaans")
                        .HasForeignKey("IdBarang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiBMN.Models.Unit", "Unit")
                        .WithMany("StokPersediaans")
                        .HasForeignKey("IdUnit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterBarang");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("SiBMN.Models.User", b =>
                {
                    b.HasOne("SiBMN.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiBMN.Models.Unit", "Unit")
                        .WithMany("Users")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("SiBMN.Models.AsetInventaris", b =>
                {
                    b.Navigation("MutasiAsets");
                });

            modelBuilder.Entity("SiBMN.Models.KategoriBarang", b =>
                {
                    b.Navigation("MasterBarangs");
                });

            modelBuilder.Entity("SiBMN.Models.MasterBarang", b =>
                {
                    b.Navigation("AsetInventaris");

                    b.Navigation("DetailPengajuans");

                    b.Navigation("StokPersediaans");
                });

            modelBuilder.Entity("SiBMN.Models.Pengajuan", b =>
                {
                    b.Navigation("DetailPengajuans");

                    b.Navigation("PenerimaanBarangs");
                });

            modelBuilder.Entity("SiBMN.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SiBMN.Models.RuangGedung", b =>
                {
                    b.Navigation("AsetInventaris");

                    b.Navigation("DetailPengajuans");

                    b.Navigation("MutasiAsets");
                });

            modelBuilder.Entity("SiBMN.Models.Unit", b =>
                {
                    b.Navigation("Pengajuans");

                    b.Navigation("RuangGedungs");

                    b.Navigation("StokPersediaans");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
